# Generated by Django 6.0.2 on 2026-04-17 00:18

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('seeker', 'Seeker'), ('recruiter', 'Recruiter')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='companyProfile',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('main_location', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('501-1000', '501–1000'), ('1000+', '1000+')], max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruiterProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_company_admin', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='accounts.account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='accounts.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='seekerProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='Resumes/')),
                ('resume_info', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('education_level', models.CharField(choices=[('High School', 'HIGH SCHOOL'), ('Associate Degree', 'ASSOCIATE'), ('Bachelor’s Degree', 'BACHELORS'), ('Master’s Degree', 'MASTERS'), ('Doctorate', 'DOCTORATE'), ('Other', 'OTHER')], default='Other', max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('anonymous_profile', models.JSONField(blank=True, default=dict)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='companyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter')], default='recruiter', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.companyprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to='accounts.recruiterprofile')),
            ],
            options={
                'unique_together': {('profile', 'company')},
            },
        ),
    ]
