# Generated by Django 6.0.2 on 2026-04-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0002_joblisting_industry_joblisting_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSwipe',
            fields=[
                ('swipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('save', 'Save')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_swipes', to='jobs.joblisting')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_swipes', to='accounts.recruiterprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_swipes', to='accounts.seekerprofile')),
            ],
            options={
                'unique_together': {('recruiter', 'seeker', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.joblisting')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.recruiterprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.seekerprofile')),
            ],
            options={
                'unique_together': {('seeker', 'recruiter', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobSwipe',
            fields=[
                ('swipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('save', 'Save')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_swipes', to='jobs.joblisting')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_swipes', to='accounts.seekerprofile')),
            ],
            options={
                'unique_together': {('seeker', 'job')},
            },
        ),
    ]
