# Generated by Django 6.0.2 on 2026-04-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('required_education', models.CharField(choices=[('High School', 'HIGH SCHOOL'), ('Associate Degree', 'ASSOCIATE'), ('Bachelor’s Degree', 'BACHELORS'), ('Master’s Degree', 'MASTERS'), ('Doctorate', 'DOCTORATE'), ('Other', 'OTHER')], default='Other', max_length=20)),
                ('min_pay', models.IntegerField()),
                ('max_pay', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.companyprofile')),
            ],
        ),
    ]
